/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.uia.is12.view;

import com.uia.is12.business.userBusiness;
import com.uia.is12.data.usersDAO;
import com.uia.is12.domain.users;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class add_users extends javax.swing.JInternalFrame {

    /**
     * Creates new form mante_usuarios
     */
    userBusiness ub; 
    public add_users() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_mante_us = new javax.swing.JLabel();
        lb_reg_us = new javax.swing.JLabel();
        lb_mant_us_name = new javax.swing.JLabel();
        mante_name = new javax.swing.JTextField();
        lb_mant_us_pass = new javax.swing.JLabel();
        mante_user_pass = new javax.swing.JPasswordField();
        lb_mant_tipo_us = new javax.swing.JLabel();
        mante_user_type = new javax.swing.JTextField();
        bt_mant_us_add = new javax.swing.JButton();
        lb_mant_us_apellidos = new javax.swing.JLabel();
        mante_user_apellidos = new javax.swing.JTextField();
        lb_mant_us_apellidos1 = new javax.swing.JLabel();
        mante_user_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        lb_mante_us.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_mante_us.setText("Mantenimiento de usuarios");

        lb_reg_us.setText("Registro de nuevos usuarios");

        lb_mant_us_name.setText("Nombre:");

        mante_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mante_nameActionPerformed(evt);
            }
        });

        lb_mant_us_pass.setText("Clave:");

        mante_user_pass.setText("jPasswordField1");

        lb_mant_tipo_us.setText("Tipo Usuario");

        bt_mant_us_add.setText("Agregar");
        bt_mant_us_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mant_us_addActionPerformed(evt);
            }
        });

        lb_mant_us_apellidos.setText("Apellidos:");

        mante_user_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mante_user_apellidosActionPerformed(evt);
            }
        });

        lb_mant_us_apellidos1.setText("Usuario");

        mante_user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mante_user_nameActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_mante_us, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_mant_us_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_mant_us_apellidos)
                                    .addComponent(mante_user_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_reg_us)
                                    .addComponent(lb_mant_us_name)
                                    .addComponent(mante_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_mant_us_apellidos1)
                                    .addComponent(mante_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mante_user_type, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_mant_tipo_us, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lb_mant_us_pass)
                                    .addComponent(mante_user_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_mante_us)
                .addGap(18, 18, 18)
                .addComponent(lb_reg_us)
                .addGap(18, 18, 18)
                .addComponent(lb_mant_us_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mante_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_mant_us_apellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mante_user_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_mant_us_apellidos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mante_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_mant_us_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mante_user_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_mant_tipo_us)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mante_user_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_mant_us_add)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mante_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mante_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mante_nameActionPerformed

    private void bt_mant_us_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mant_us_addActionPerformed
        // TODO add your handling code here:
      users u = new users(mante_user_name.getText(),mante_user_pass.getText(),
                          mante_name.getText(),mante_user_apellidos.getText(),mante_user_type.getText());
      ub = new userBusiness();  
        try {
            ub.add(u);
            JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo crear el usuario");
            Logger.getLogger(add_users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_mant_us_addActionPerformed

    private void mante_user_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mante_user_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mante_user_apellidosActionPerformed

    private void mante_user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mante_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mante_user_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_mant_us_add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_mant_tipo_us;
    private javax.swing.JLabel lb_mant_us_apellidos;
    private javax.swing.JLabel lb_mant_us_apellidos1;
    private javax.swing.JLabel lb_mant_us_name;
    private javax.swing.JLabel lb_mant_us_pass;
    private javax.swing.JLabel lb_mante_us;
    private javax.swing.JLabel lb_reg_us;
    private javax.swing.JTextField mante_name;
    private javax.swing.JTextField mante_user_apellidos;
    private javax.swing.JTextField mante_user_name;
    private javax.swing.JPasswordField mante_user_pass;
    private javax.swing.JTextField mante_user_type;
    // End of variables declaration//GEN-END:variables
}
