/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uia.is12.view;

import com.uia.is12.business.proyectoBusiness;
import com.uia.is12.business.userBusiness;
import com.uia.is12.domain.proyecto;
import com.uia.is12.domain.users;
import java.awt.Checkbox;
import java.awt.List;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michael
 */
public class mant_proy extends javax.swing.JInternalFrame implements KeyListener {

    /**
     * Creates new form mant_users
     */
    proyectoBusiness ub;
    LinkedList<proyecto> l;
    int numReg;
    String listaDel;

    public mant_proy() throws SQLException {
        initComponents();
        t_proy.addKeyListener(this);
        ub = new proyectoBusiness();
        l = ub.select_proy();
        listaDel = "";
        numReg = l.size();
        for (int i = 0; i < numReg; i++) { // Recorriendo Los Datos que se Encuentran en el Arraylist
            t_proy.setValueAt(l.get(i).getProyecto_id(), i, 0);
            t_proy.setValueAt(l.get(i).getProyecto_name(), i, 1);
            t_proy.setValueAt(l.get(i).getProyecto_desc(), i, 2);
            t_proy.setValueAt(l.get(i).getEstado(), i, 3);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        bt_guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_proy = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bt_guardar.setText("Guardar Datos");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        t_proy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(t_proy);
        if (t_proy.getColumnModel().getColumnCount() > 0) {
            t_proy.getColumnModel().getColumn(0).setResizable(false);
            t_proy.getColumnModel().getColumn(1).setResizable(false);
            t_proy.getColumnModel().getColumn(2).setResizable(false);
            t_proy.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(bt_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)))
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_guardar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            int control = numRegTable();
            for (int i = 0; i < control; i++) { // Recorriendo Los Datos que se Encuentran en el Arraylist
                if (i < numReg) {
                    if ((((l.get(i).getProyecto_name()) != ((String) (t_proy.getValueAt(i, 1))))
                            || ((l.get(i).getProyecto_desc()) != ((String) (t_proy.getValueAt(i, 2))))
                            || ((l.get(i).getEstado()) != ((String) (t_proy.getValueAt(i, 3)))))) {
                        try {
                            ub = new proyectoBusiness();

                            ub.update(new proyecto((int) (t_proy.getValueAt(i, 0)), ((String) (t_proy.getValueAt(i, 1))),
                                    ((String) (t_proy.getValueAt(i, 2))), ((String) (t_proy.getValueAt(i, 3)))));
                        } catch (SQLException ex) {
                            Logger.getLogger(mant_proy.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                } else {
                    try {
                        ub = new proyectoBusiness();
                        ub.add(new proyecto(((String) (t_proy.getValueAt(i, 1))),
                                ((String) (t_proy.getValueAt(i, 2))), ((String) (t_proy.getValueAt(i, 3)))));
                    } catch (SQLException ex) {
                        Logger.getLogger(mant_proy.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            try {
                ub.deleteGroup(listaDel);
            } catch (SQLException ex) {
                Logger.getLogger(mant_proy.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (StringIndexOutOfBoundsException e) {

        }
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public int numRegTable() {
        int i = 0;
        try {
            while (((String) (t_proy.getValueAt(i, 1))).length() > 0) {
                i++;
            }
            return i;
        } catch (NullPointerException | IndexOutOfBoundsException e) {
            return i;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable t_proy;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {

        if (e.getKeyCode() == KeyEvent.VK_DELETE) {
            listaDel = listaDel + "," + (int) (t_proy.getValueAt(t_proy.getSelectedRow(), 0));
            DefaultTableModel dtm = (DefaultTableModel) t_proy.getModel(); //TableProducto es el nombre de mi tabla ;) 
            dtm.removeRow(t_proy.getSelectedRow());
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
