/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uia.is12.view;

import com.uia.is12.business.issuesBusiness;
import com.uia.is12.business.proyectoBusiness;
import com.uia.is12.business.userBusiness;
import com.uia.is12.domain.proyecto;
import com.uia.is12.domain.issues;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michael
 */
public class mant_issues extends javax.swing.JInternalFrame implements KeyListener {

    /**
     * Creates new form mant_users
     */
    issuesBusiness ub;
    LinkedList<issues> l;
    int numReg;
    String listaDel;

    public mant_issues() throws SQLException {
        initComponents();
        t_issues.addKeyListener(this);
        ub = new issuesBusiness();
        l = ub.select_issues(1);
        listaDel = "";
        numReg = l.size();
        for (int i = 0; i < numReg; i++) { // Recorriendo Los Datos que se Encuentran en el Arraylist
            t_issues.setValueAt(l.get(i).getIssue_id(), i, 0);
            t_issues.setValueAt(l.get(i).getIssue_desc(), i, 1);
            t_issues.setValueAt(l.get(i).getEstado(), i, 2);
            t_issues.setValueAt(l.get(i).getUser_id(), i, 3);
            t_issues.setValueAt(l.get(i).getFecha_digita(), i, 4);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        bt_guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_issues = new javax.swing.JTable();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bt_guardar.setText("Guardar Datos");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        t_issues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Estado", "Creado por", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(t_issues);
        if (t_issues.getColumnModel().getColumnCount() > 0) {
            t_issues.getColumnModel().getColumn(0).setResizable(false);
            t_issues.getColumnModel().getColumn(1).setResizable(false);
            t_issues.getColumnModel().getColumn(2).setResizable(false);
            t_issues.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(bt_guardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            int control = numRegTable();
            for (int i = 0; i < control; i++) { // Recorriendo Los Datos que se Encuentran en el Arraylist
                JOptionPane.showMessageDialog(null, "for");
                if (i < numReg) {
                    JOptionPane.showMessageDialog(null, "1");
                    if ((((l.get(i).getIssue_desc()) != ((String) (t_issues.getValueAt(i, 1))))
                            || ((l.get(i).getEstado()) != ((String) (t_issues.getValueAt(i, 2)))))) {
                        JOptionPane.showMessageDialog(null, "2");
                        try {
                            ub = new issuesBusiness();
                            JOptionPane.showMessageDialog(null, "update");
                            ub.update(new issues(1, ((int) (t_issues.getValueAt(i, 0))),
                                    ((String) (t_issues.getValueAt(i, 1))), 1,
                                    ((String) (t_issues.getValueAt(i, 4))),((String) (t_issues.getValueAt(i, 3)))));
                        } catch (SQLException ex) {
                            Logger.getLogger(mant_issues.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                } else {
                    try {
                        ub = new issuesBusiness();
                        ub.add(new issues(1, 1,
                                    ((String) (t_issues.getValueAt(i, 1))), 1,
                                    ((String) (t_issues.getValueAt(i, 4))),((String) (t_issues.getValueAt(i, 3)))));
                    } catch (SQLException ex) {
                        Logger.getLogger(mant_issues.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            try {
                ub.deleteGroup("1",listaDel);
            } catch (SQLException ex) {
                Logger.getLogger(mant_issues.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (StringIndexOutOfBoundsException e) {

        }
    }//GEN-LAST:event_bt_guardarActionPerformed

    public int numRegTable() {
        int i = 0;
        try {
            while (((String) (t_issues.getValueAt(i, 1))).length() > 0) {
                i++;
            }
            return i;
        } catch (NullPointerException | IndexOutOfBoundsException e) {
            return i;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guardar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable t_issues;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {

        if (e.getKeyCode() == KeyEvent.VK_DELETE) {
            listaDel = listaDel + "," + (int) (t_issues.getValueAt(t_issues.getSelectedRow(), 0));
            DefaultTableModel dtm = (DefaultTableModel) t_issues.getModel(); //TableProducto es el nombre de mi tabla ;) 
            dtm.removeRow(t_issues.getSelectedRow());
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
