/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uia.is12.view;

import com.uia.is12.business.userBusiness;
import com.uia.is12.domain.users;
import java.awt.Checkbox;
import java.awt.List;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michael
 */
public class mant_users extends javax.swing.JInternalFrame implements KeyListener {

    /**
     * Creates new form mant_users
     */
    userBusiness ub;
    LinkedList<users> l;
    int numReg;
    String listaDel;

    public mant_users() throws SQLException {
        initComponents();
        t_users.addKeyListener(this);
        ub = new userBusiness();
        l = ub.select_users();
        listaDel = "";
        numReg = l.size();
        for (int i = 0; i < numReg; i++) { // Recorriendo Los Datos que se Encuentran en el Arraylist
            t_users.setValueAt(l.get(i).getUser_id(), i, 0);
            t_users.setValueAt(l.get(i).getName(), i, 1);
            t_users.setValueAt(l.get(i).getLast_name(), i, 2);
            t_users.setValueAt(l.get(i).getUser_name(), i, 3);
            t_users.setValueAt(l.get(i).getUser_pass(), i, 4);
            t_users.setValueAt(l.get(i).getUser_type(), i, 5);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_users = new javax.swing.JTable();
        bt_guardar = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        t_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                " ID", "Nombre", "Apellidos", "Usuario", "Clave", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_users);
        if (t_users.getColumnModel().getColumnCount() > 0) {
            t_users.getColumnModel().getColumn(0).setResizable(false);
            t_users.getColumnModel().getColumn(1).setResizable(false);
            t_users.getColumnModel().getColumn(2).setResizable(false);
            t_users.getColumnModel().getColumn(3).setResizable(false);
            t_users.getColumnModel().getColumn(4).setResizable(false);
            t_users.getColumnModel().getColumn(5).setResizable(false);
        }

        bt_guardar.setText("Guardar Datos");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(bt_guardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            int control = numRegTable();
            for (int i = 0; i < control; i++) { // Recorriendo Los Datos que se Encuentran en el Arraylist
                if (i < numReg) {
                    if ((((l.get(i).getName()) != ((String) (t_users.getValueAt(i, 1))))
                            || ((l.get(i).getLast_name()) != ((String) (t_users.getValueAt(i, 2))))
                            || ((l.get(i).getUser_name()) != ((String) (t_users.getValueAt(i, 3))))
                            || ((l.get(i).getUser_pass()) != ((String) (t_users.getValueAt(i, 4))))
                            || ((l.get(i).getUser_type()) != ((String) (t_users.getValueAt(i, 5)))))) {
                        try {
                            ub = new userBusiness();

                            ub.update(new users((int) (t_users.getValueAt(i, 0)), ((String) (t_users.getValueAt(i, 3))),
                                    ((String) (t_users.getValueAt(i, 4))), ((String) (t_users.getValueAt(i, 1))),
                                    ((String) (t_users.getValueAt(i, 2))), ((String) (t_users.getValueAt(i, 5)))));
                        } catch (SQLException ex) {
                            Logger.getLogger(mant_users.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                } else {
                    try {
                        ub = new userBusiness();
                        ub.add(new users(((String) (t_users.getValueAt(i, 3))),
                                ((String) (t_users.getValueAt(i, 4))), ((String) (t_users.getValueAt(i, 1))),
                                ((String) (t_users.getValueAt(i, 2))), ((String) (t_users.getValueAt(i, 5)))));
                    } catch (SQLException ex) {
                        Logger.getLogger(mant_users.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            try {
                ub.deleteGroup(listaDel);
            } catch (SQLException ex) {
                Logger.getLogger(mant_users.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (StringIndexOutOfBoundsException e) {

        }
    }//GEN-LAST:event_bt_guardarActionPerformed

    public int numRegTable() {
        int i = 0;
        try {
            while (((String) (t_users.getValueAt(i, 3))).length() > 0) {
                i++;
            }
            return i;
        } catch (NullPointerException | IndexOutOfBoundsException e) {
            return i;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guardar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable t_users;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {

        if (e.getKeyCode() == KeyEvent.VK_DELETE) {
            listaDel = listaDel + "," + (int) (t_users.getValueAt(t_users.getSelectedRow(), 0));
            DefaultTableModel dtm = (DefaultTableModel) t_users.getModel(); //TableProducto es el nombre de mi tabla ;) 
            dtm.removeRow(t_users.getSelectedRow());
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
