/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uia.is12.view;

import com.uia.is12.business.proyectoBusiness;
import com.uia.is12.domain.proyecto;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class proyectos extends javax.swing.JInternalFrame {

    /**
     * Creates new form proyectos
     */
    proyectoBusiness pb;

    public proyectos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_proyectos = new javax.swing.JLabel();
        proyecto_name = new javax.swing.JTextField();
        lb_nom_proy = new javax.swing.JLabel();
        lb_desc_proy = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        proyecto_desc = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb_estado_proy = new javax.swing.JLabel();
        estado_proyecto = new javax.swing.JTextField();
        lb_estado_proy1 = new javax.swing.JLabel();
        lb_estado_proy2 = new javax.swing.JLabel();
        lb_estado_proy3 = new javax.swing.JLabel();

        lb_proyectos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_proyectos.setText("Creación de Proyecto");

        proyecto_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyecto_nameActionPerformed(evt);
            }
        });

        lb_nom_proy.setText("Nombre de Proyecto");

        lb_desc_proy.setText("Descripción:");

        jScrollPane1.setViewportView(proyecto_desc);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lb_estado_proy.setText("Estado del Proyecto");

        lb_estado_proy1.setText("ABR = Abierto");

        lb_estado_proy2.setText("CER = Cerrado");

        lb_estado_proy3.setText("EJEC = Ejecución");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_proyectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addComponent(lb_desc_proy)
                                .addComponent(lb_nom_proy)
                                .addComponent(proyecto_name)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_estado_proy)
                                    .addComponent(estado_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_estado_proy2)
                                    .addComponent(lb_estado_proy1)
                                    .addComponent(lb_estado_proy3))))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lb_proyectos)
                .addGap(18, 18, 18)
                .addComponent(lb_nom_proy)
                .addGap(18, 18, 18)
                .addComponent(proyecto_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_desc_proy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_estado_proy)
                    .addComponent(lb_estado_proy1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_estado_proy2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_estado_proy3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void proyecto_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyecto_nameActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_proyecto_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pb = new proyectoBusiness();

        if (proyecto_name.getText().length()>0 && proyecto_desc.getText().length() > 0 && estado_proyecto.getText().length() > 0) {
            try {
                proyecto p = new proyecto(proyecto_name.getText(), proyecto_desc.getText(), estado_proyecto.getText());
                pb.add(p);
                JOptionPane.showMessageDialog(null, "El proyecto ha sido guardado con exito");
            } catch (SQLException ex) {
                Logger.getLogger(proyectos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo crear el proyecto");
            Logger.getLogger(proyectos.class.getName()).log(Level.SEVERE, null);


    }//GEN-LAST:event_jButton1ActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estado_proyecto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_desc_proy;
    private javax.swing.JLabel lb_estado_proy;
    private javax.swing.JLabel lb_estado_proy1;
    private javax.swing.JLabel lb_estado_proy2;
    private javax.swing.JLabel lb_estado_proy3;
    private javax.swing.JLabel lb_nom_proy;
    private javax.swing.JLabel lb_proyectos;
    private javax.swing.JTextPane proyecto_desc;
    private javax.swing.JTextField proyecto_name;
    // End of variables declaration//GEN-END:variables
}
